language: android

env:
  global:
    - ANDROID_API_LEVEL=28
    - EMULATOR_API_LEVEL=19
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - ANDROID_TARGET=android-$ANDROID_API_LEVEL
    - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)

android:
  components:
    - tools
    - platform-tools
    - android-$EMULATOR_API_LEVEL
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - addon-google_apis-google-$ANDROID_API_LEVEL
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository
    - extra-google-play_billing
    - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL

  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

script:
  ./gradlew app:clean app:test --no-daemon

